-- ============================================
-- SEATs: Smart Electronic Attendance Tracking
-- PostgreSQL Schema — All 5 Tables
-- ============================================
-- Run this in psql:
--   psql -U postgres -d seats_db -f schema.sql
-- Or paste directly into psql after connecting.
-- ============================================


-- Drop tables in reverse dependency order (safe re-run)
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS session_students CASCADE;
DROP TABLE IF EXISTS pending_registrations CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS students CASCADE;


-- ============================================
-- 1. students
--    One row per registered student.
--    uid is the NFC card UID (e.g. "33:8c:f2:12")
-- ============================================
CREATE TABLE students (
    id            SERIAL PRIMARY KEY,
    uid           VARCHAR(20)  NOT NULL UNIQUE,
    name          VARCHAR(100) NOT NULL,
    student_id    VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(100),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    registered_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Fast lookup by card UID on every tap
CREATE INDEX idx_students_uid ON students(uid);


-- ============================================
-- 2. sessions
--    One row per lecture / lab session.
--    status flows: created → active → ended
-- ============================================
CREATE TABLE sessions (
    id              SERIAL PRIMARY KEY,
    session_code    VARCHAR(100) NOT NULL UNIQUE,
    course_name     VARCHAR(100) NOT NULL,
    session_date    DATE         NOT NULL,
    start_time      TIMESTAMP,
    end_time        TIMESTAMP,
    total_students  INTEGER      NOT NULL DEFAULT 0,
    present_count   INTEGER      NOT NULL DEFAULT 0,
    occurrence      INTEGER      NOT NULL DEFAULT 1,  -- lecture number 1, 2, 3…
    status          VARCHAR(20)  NOT NULL DEFAULT 'created'
                        CHECK (status IN ('created', 'active', 'ended')),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sessions_status ON sessions(status);
CREATE INDEX idx_sessions_date   ON sessions(session_date);


-- ============================================
-- 3. session_students
--    Which students are assigned to a session.
--    Populated before the session starts.
-- ============================================
CREATE TABLE session_students (
    id           SERIAL PRIMARY KEY,
    session_id   INTEGER      NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    uid          VARCHAR(20)  NOT NULL,
    student_name VARCHAR(100) NOT NULL,
    assigned_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- A student can only be assigned once per session
    UNIQUE (session_id, uid)
);

CREATE INDEX idx_session_students_session ON session_students(session_id);
CREATE INDEX idx_session_students_uid     ON session_students(uid);


-- ============================================
-- 4. attendance
--    One row per card tap (present or denied).
--    This is what the ESP32 writes to via the API.
-- ============================================
CREATE TABLE attendance (
    id            SERIAL PRIMARY KEY,
    record_id     VARCHAR(50)  NOT NULL UNIQUE,   -- generated by API, e.g. "ATT-20250324-001"
    uid           VARCHAR(20)  NOT NULL,
    student_name  VARCHAR(100) NOT NULL DEFAULT 'Unknown',
    session_id    INTEGER      REFERENCES sessions(id) ON DELETE SET NULL,
    occurrence    INTEGER,
    nfc_timestamp TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status        VARCHAR(20)  NOT NULL DEFAULT 'present'
                      CHECK (status IN ('present', 'denied')),
    device        VARCHAR(50)  NOT NULL DEFAULT 'ESP32-C6'
);

CREATE INDEX idx_attendance_uid       ON attendance(uid);
CREATE INDEX idx_attendance_session   ON attendance(session_id);
CREATE INDEX idx_attendance_timestamp ON attendance(nfc_timestamp);


-- ============================================
-- 5. pending_registrations
--    Admin creates a "slot" with name/email/id,
--    then the student taps their card to link it.
--    status flows: waiting → completed / cancelled
-- ============================================
CREATE TABLE pending_registrations (
    id           SERIAL PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    student_id   VARCHAR(50)  NOT NULL,
    email        VARCHAR(100),
    uid          VARCHAR(20),                      -- NULL until card is tapped
    status       VARCHAR(20)  NOT NULL DEFAULT 'waiting'
                     CHECK (status IN ('waiting', 'completed', 'cancelled')),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP                         -- filled when card is linked
);

CREATE INDEX idx_pending_status ON pending_registrations(status);


-- ============================================
-- Seed: 3 students already hardcoded in ESP32
--       (matches the allowedUIDs array)
-- ============================================
INSERT INTO students (uid, name, student_id, email) VALUES
    ('33:8c:f2:12', 'Pratik',   'STU001', 'pratik@example.com'),
    ('f3:fc:9b:0f', 'Tanmay',   'STU002', 'tanmay@example.com'),
    ('33:fc:8c:0f', 'Student3', 'STU003', 'student3@example.com');


-- ============================================
-- Done. Verify with:
--   \dt               — list all tables
--   SELECT * FROM students;
-- ============================================
